export const GEMINI_EMBEDDING_MODEL = {
  TEXT_004: "text-embedding-004",
  GEMINI_EXP_0307: "gemini-embedding-exp-03-07",
};

export enum GeminiEmbeddedTaskType {
  SEMANTIC_SIMILARITY = "SEMANTIC_SIMILARITY",
  CLASSIFICATION = "CLASSIFICATION",
  CLUSTERING = "CLUSTERING",
  RETRIEVAL_DOCUMENT = "RETRIEVAL_DOCUMENT",
  RETRIEVAL_QUERY = "RETRIEVAL_QUERY",
  QUESTION_ANSWERING = "QUESTION_ANSWERING",
  FACT_VERIFICATION = "FACT_VERIFICATION",
  CODE_RETRIEVAL_QUERY = "CODE_RETRIEVAL_QUERY",
};
